name: Mark stale issues and pull requests

on:
  schedule:
    # This cron expression schedules the workflow to run daily at 13:34 UTC
    - cron: '34 13 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. If no further activity occurs, it will be closed.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity. If no further activity occurs, it will be closed.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
